In [2]:
%pip install langchain_ollama pandas

Collecting langchain_ollama
  Downloading langchain_ollama-0.3.7-py3-none-any.whl.metadata (2.1 kB)
Collecting pandas
  Downloading pandas-2.3.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting ollama<1.0.0,>=0.5.3 (from langchain_ollama)
  Downloading ollama-0.5.3-py3-none-any.whl.metadata (4.3 kB)
Collecting langchain-core<1.0.0,>=0.3.74 (from langchain_ollama)
  Downloading langchain_core-0.3.75-py3-none-any.whl.metadata (5.7 kB)
Collecting langsmith>=0.3.45 (from langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading langsmith-0.4.21-py3-none-any.whl.metadata (14 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
Collecting jsonpatch<2.0,>=1.33 (from langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting PyYAML>=5.3 (from langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading PyYAML-6.0.2-cp311-cp311-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: typing-extensions>=4.7 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from langchain-core<1.0.0,>=0.3.74->langchain_ollama) (4.15.0)
Requirement already satisfied: packaging>=23.2 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from langchain-core<1.0.0,>=0.3.74->langchain_ollama) (25.0)
Collecting pydantic>=2.7.4 (from langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading pydantic-2.11.7-py3-none-any.whl.metadata (67 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting httpx>=0.27 (from ollama<1.0.0,>=0.5.3->langchain_ollama)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting numpy>=1.23.2 (from pandas)
  Downloading numpy-2.3.2-cp311-cp311-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting anyio (from httpx>=0.27->ollama<1.0.0,>=0.5.3->langchain_ollama)
  Downloading anyio-4.10.0-py3-none-any.whl.metadata (4.0 kB)
Collecting certifi (from httpx>=0.27->ollama<1.0.0,>=0.5.3->langchain_ollama)
  Downloading certifi-2025.8.3-py3-none-any.whl.metadata (2.4 kB)
Collecting httpcore==1.* (from httpx>=0.27->ollama<1.0.0,>=0.5.3->langchain_ollama)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx>=0.27->ollama<1.0.0,>=0.5.3->langchain_ollama)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx>=0.27->ollama<1.0.0,>=0.5.3->langchain_ollama)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting orjson>=3.9.14 (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading orjson-3.11.3-cp311-cp311-win_amd64.whl.metadata (43 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting requests>=2.0.0 (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting zstandard>=0.23.0 (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading zstandard-0.24.0-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
Collecting annotated-types>=0.6.0 (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.33.2 (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading pydantic_core-2.33.2-cp311-cp311-win_amd64.whl.metadata (6.9 kB)
Collecting typing-inspection>=0.4.0 (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading typing_inspection-0.4.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: six>=1.5 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests>=2.0.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading charset_normalizer-3.4.3-cp311-cp311-win_amd64.whl.metadata (37 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.0.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.74->langchain_ollama)
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting sniffio>=1.1 (from anyio->httpx>=0.27->ollama<1.0.0,>=0.5.3->langchain_ollama)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Downloading langchain_ollama-0.3.7-py3-none-any.whl (24 kB)
Downloading langchain_core-0.3.75-py3-none-any.whl (443 kB)
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading ollama-0.5.3-py3-none-any.whl (13 kB)
Downloading tenacity-9.1.2-py3-none-any.whl (28 kB)
Downloading pandas-2.3.2-cp311-cp311-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   -------------------------------------- - 11.0/11.3 MB 49.1 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.3 MB 50.3 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 26.2 MB/s  0:00:00
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading jsonpointer-3.0.0-py2.py3-none-any.whl (7.6 kB)
Downloading langsmith-0.4.21-py3-none-any.whl (378 kB)
Downloading pydantic-2.11.7-py3-none-any.whl (444 kB)
Downloading pydantic_core-2.33.2-cp311-cp311-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 54.5 MB/s  0:00:00
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading numpy-2.3.2-cp311-cp311-win_amd64.whl (13.1 MB)
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
   ------------------------------- -------- 10.2/13.1 MB 49.1 MB/s eta 0:00:01
   ---------------------------------------- 13.1/13.1 MB 43.2 MB/s  0:00:00
Downloading orjson-3.11.3-cp311-cp311-win_amd64.whl (131 kB)
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading PyYAML-6.0.2-cp311-cp311-win_amd64.whl (161 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.3-cp311-cp311-win_amd64.whl (107 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
Downloading certifi-2025.8.3-py3-none-any.whl (161 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Downloading typing_inspection-0.4.1-py3-none-any.whl (14 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Downloading zstandard-0.24.0-cp311-cp311-win_amd64.whl (505 kB)
Downloading anyio-4.10.0-py3-none-any.whl (107 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Installing collected packages: pytz, zstandard, urllib3, tzdata, typing-inspection, tenacity, sniffio, PyYAML, pydantic-core, orjson, numpy, jsonpointer, idna, h11, charset_normalizer, certifi, annotated-types, requests, pydantic, pandas, jsonpatch, httpcore, anyio, requests-toolbelt, httpx, ollama, langsmith, langchain-core, langchain_ollama

   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   ----------------------------------------  0/29 [pytz]
   - --------------------------------------  1/29 [zstandard]
   - --------------------------------------  1/29 [zstandard]
   - --------------------------------------  1/29 [zstandard]
   - --------------------------------------  1/29 [zstandard]
   -- -------------------------------------  2/29 [urllib3]
   -- -------------------------------------  2/29 [urllib3]
   -- -------------------------------------  2/29 [urllib3]
   -- -------------------------------------  2/29 [urllib3]
   -- -------------------------------------  2/29 [urllib3]
   -- -------------------------------------  2/29 [urllib3]
   -- -------------------------------------  2/29 [urllib3]
   -- -------------------------------------  2/29 [urllib3]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]
   ---- -----------------------------------  3/29 [tzdata]

In [9]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import os
from langchain_ollama import OllamaLLM

In [35]:
# loading excel
def load_data():
    df = pd.read_excel("D:\\Mestrado\\teste\\langchain_test\\data\\dados.xlsx", header=6)
    return df

# runing function
data = load_data()

# to see your directory: os.getcwd()

print(data.shape)
data.head()

(110967, 28)

,Solicitacao,Bem/Localiz.,Desc.Bem/Loc,Centro Trab.,Nome Locali.,Ramal,Sublocal,data_abertura,Hr. Abertura,Dt. Falha,...,Solicitante,Reclamante,Executante,Nome Exec.,Contador,Tipo de SS,Ret.Operacao,Vandalismo,Criticidade,Tipo Solicit
0,000002,SINCDVROD,CIRCUITO DE VIA RODOVIARIA,201ELO,ESTACAO RODOVIARIA,8667,ROTA 36.30 NAO CANCELA,2013-06-15 00:00:00,01:06,2013-06-15 00:00:00,...,000142,SCHULER/CCO,ELO004,ELO004 - SINALIZACAO,0,Operacional,Não,Nao,NaN,NaN
1,000003,SINCDVROD,CIRCUITO DE VIA RODOVIARIA,201ELO,ESTACAO RODOVIARIA,8667,ROTA 44.36 NAO ALINHA,2013-06-15 00:00:00,01:09,2013-06-15 00:00:00,...,000142,SCHULER/CCO,RES001,RES001 - RESTABELECI,0,Operacional,Não,Nao,NaN,NaN
2,000004,SINCDVROD,CIRCUITO DE VIA RODOVIARIA,201ELO,ESTACAO RODOVIARIA,8667,ROTA 36.40 DE TRAFEGO,2013-06-15 00:00:00,03:43,2013-06-15 00:00:00,...,000142,CARLOS/CCO,RES001,RES001 - RESTABELECI,0,Operacional,Não,Nao,NaN,NaN
3,000005,BILMAG,BILHETAGEM 15 - MANGUEIRA,201ELO,ESTACAO MANGUEIRA,8655,POS DA BILHETERIA.1,2013-06-15 00:00:00,06:19,2013-06-15 00:00:00,...,000136,NILDETE,ELO003,ELO003 - BILHETAGEM,0,Operacional,Não,Nao,NaN,NaN
4,000006,SINCDVJOA,CIRCUITO DE VIA JOANA BEZERRA,201ELO,ESTACAO JOANA BEZERRA,8889,CDV OEST.1,2013-06-15 00:00:00,07:25,2013-06-15 00:00:00,...,000136,RUBENS,RES001,RES001 - RESTABELECI,0,Operacional,Não,Nao,NaN,NaN

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110967 entries, 0 to 110966
Data columns (total 28 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Solicitacao      110963 non-null  object
 1   Bem/Localiz.     110961 non-null  object
 2   Desc.Bem/Loc     110918 non-null  object
 3   Centro Trab.     94934 non-null   object
 4   Nome Locali.     110555 non-null  object
 5   Ramal            110943 non-null  object
 6   Sublocal         110961 non-null  object
 7   data_abertura    110961 non-null  object
 8   Hr. Abertura     110961 non-null  object
 9   Dt. Falha        110961 non-null  object
 10  Hr. Falha        110961 non-null  object
 11  Situacao S.S     110961 non-null  object
 12  Prioridade       108693 non-null  object
 13  Descricao        110636 non-null  object
 14  data_fechamento  110961 non-null  object
 15  Hora Enc.        110961 non-null  object
 16  Solucao SS       105582 non-null  object
 17  Ordem Servic     93068 non-null   object
 18  Solicitante      110961 non-null  object
 19  Reclamante       110961 non-null  object
 20  Executante       108693 non-null  object
 21  Nome Exec.       108693 non-null  object
 22  Contador         110963 non-null  object
 23  Tipo de SS       110961 non-null  object
 24  Ret.Operacao     110961 non-null  object
 25  Vandalismo       110961 non-null  object
 26  Criticidade      1404 non-null    object
 27  Tipo Solicit     31035 non-null   object
dtypes: object(28)
memory usage: 23.7+ MB

In [37]:
data.isna().sum()

Solicitacao             4
Bem/Localiz.            6
Desc.Bem/Loc           49
Centro Trab.        16033
Nome Locali.          412
Ramal                  24
Sublocal                6
data_abertura           6
Hr. Abertura            6
Dt. Falha               6
Hr. Falha               6
Situacao S.S            6
Prioridade           2274
Descricao             331
data_fechamento         6
Hora Enc.               6
Solucao SS           5385
Ordem Servic        17899
Solicitante             6
Reclamante              6
Executante           2274
Nome Exec.           2274
Contador                4
Tipo de SS              6
Ret.Operacao            6
Vandalismo              6
Criticidade        109563
Tipo Solicit        79932
dtype: int64

In [38]:
data.describe()

,Solicitacao,Bem/Localiz.,Desc.Bem/Loc,Centro Trab.,Nome Locali.,Ramal,Sublocal,data_abertura,Hr. Abertura,Dt. Falha,...,Solicitante,Reclamante,Executante,Nome Exec.,Contador,Tipo de SS,Ret.Operacao,Vandalismo,Criticidade,Tipo Solicit
count,110963,110961,110918,94934,110555,110943,110961,110961,110961,110961,...,110961,110961,108693,108693,110963,110961,110961,110961,1404,31035
unique,109560,4464,4236,25,244,1222,18746,2726,1441,2810,...,34,25612,47,47,8948,5,3,3,1,2
top,Solicitacao,Bem/Localiz.,Desc.Bem/Loc,101MAC,ESTACAO RECIFE,8889,CARRO 1,Dt. Abertura,Hr. Abertura,Dt. Falha,...,000406,Reclamante,MAC001,MAC001 - TUE CORRETI,0,Operacional,Não,Nao,Criticidade,Incidente
freq,1404,1404,1404,25704,4436,24024,12335,1404,1404,1404,...,14956,1404,34570,34570,82711,105422,71509,108384,1404,29631

In [39]:
print(data.columns.tolist())

['Solicitacao', 'Bem/Localiz.', 'Desc.Bem/Loc', 'Centro Trab.', 'Nome Locali.', 'Ramal', 'Sublocal', 'data_abertura', 'Hr. Abertura', 'Dt. Falha', 'Hr. Falha', 'Situacao S.S', 'Prioridade', 'Descricao', 'data_fechamento', 'Hora Enc.', 'Solucao SS', 'Ordem Servic', 'Solicitante', 'Reclamante', 'Executante', 'Nome Exec.', 'Contador', 'Tipo de SS', 'Ret.Operacao', 'Vandalismo', 'Criticidade', 'Tipo Solicit']

In [43]:
data.columns = data.columns.str.strip()

data['data_abertura'] = pd.to_datetime(data['data_abertura'], format="%d/%m/%Y", errors='coerce')
data['Dt. Falha'] = pd.to_datetime(data['Dt. Falha'], format="%d/%m/%Y", errors='coerce')
data['data_fechamento'] = pd.to_datetime(data['data_fechamento'], format="%d/%m/%Y", errors='coerce')

# Limpar espaços e quebras de linha
data['Hr. Abertura'] = data['Hr. Abertura'].astype(str).str.strip().str.replace(r'\s+', '', regex=True)
data['Hr. Falha'] = data['Hr. Falha'].astype(str).str.strip().str.replace(r'\s+', '', regex=True)
data['Hora Enc.'] = data['Hora Enc.'].astype(str).str.strip().str.replace(r'\s+', '', regex=True)

# Converter horas (opcional, se quiser manter como string pode pular)
data['Hr. Abertura'] = pd.to_datetime(data['Hr. Abertura'], format="%H:%M", errors='coerce').dt.time
data['Hr. Falha'] = pd.to_datetime(data['Hr. Falha'], format="%H:%M", errors='coerce').dt.time
data['Hora Enc.'] = pd.to_datetime(data['Hora Enc.'], format="%H:%M", errors='coerce').dt.time

# Converter colunas numéricas
data['Contador'] = pd.to_numeric(data['Contador'], errors='coerce')

# Outras colunas de texto podem continuar como string
texto_cols = [
    'Solicitacao', 'Bem/Localiz.', 'Desc.Bem/Loc', 'Centro Trab.', 'Nome Locali.',
    'Ramal', 'Sublocal', 'Situacao S.S', 'Prioridade', 'Descricao',
    'Solucao SS', 'Ordem Servic', 'Solicitante', 'Reclamante', 'Executante',
    'Nome Exec.', 'Tipo de SS', 'Ret.Operacao', 'Vandalismo', 'Criticidade', 'Tipo Solicit'
]
data[texto_cols] = data[texto_cols].astype("string")

# Conferir tipos
print(data.dtypes)

Solicitacao        string[python]
Bem/Localiz.       string[python]
Desc.Bem/Loc       string[python]
Centro Trab.       string[python]
Nome Locali.       string[python]
Ramal              string[python]
Sublocal           string[python]
data_abertura      datetime64[ns]
Hr. Abertura               object
Dt. Falha          datetime64[ns]
Hr. Falha                  object
Situacao S.S       string[python]
Prioridade         string[python]
Descricao          string[python]
data_fechamento    datetime64[ns]
Hora Enc.                  object
Solucao SS         string[python]
Ordem Servic       string[python]
Solicitante        string[python]
Reclamante         string[python]
Executante         string[python]
Nome Exec.         string[python]
Contador                  float64
Tipo de SS         string[python]
Ret.Operacao       string[python]
Vandalismo         string[python]
Criticidade        string[python]
Tipo Solicit       string[python]
dtype: object

In [19]:
from langchain_ollama import OllamaLLM  # se estiver usando LangChain + Ollama

# Crie o LLM informando o modelo
client = OllamaLLM(model="mistral")  # ou "mistral-7b" dependendo do que você baixou

def testing_question(question):
    """
    Summarizes the text using Mistral via Ollama.
    """
    summary = client.predict(f"You are a helpful assistant that summarizes text.\n\nUser: {question}\nAssistant:")
    return summary

# Teste
print(testing_question("Write a story about BTC"))

C:\Users\Dahise\AppData\Local\Temp\ipykernel_6180\1636846597.py:10: LangChainDeprecationWarning: The method `BaseLLM.predict` was deprecated in langchain-core 0.1.7 and will be removed in 1.0. Use :meth:`~invoke` instead.
  summary = client.predict(f"You are a helpful assistant that summarizes text.\n\nUser: {question}\nAssistant:")

 Title: The Journey of Bitcoin (BTC)

In the world of digital currency, Bitcoin (BTC) stands as a trailblazer. Created in 2008 by an anonymous individual or group using the pseudonym Satoshi Nakamoto, Bitcoin was designed to be a decentralized, peer-to-peer digital cash system. The concept was outlined in a whitepaper titled "Bitcoin: A Peer-to-Peer Electronic Cash System."

In January 2009, the first-ever transaction of BTC took place when Satoshi mined the genesis block, rewarding himself with 50 BTC. The digital coins initially struggled to gain traction due to their novelty and lack of widespread understanding. However, their potential as a secure and borderless form of currency began to attract attention.

As more people joined the Bitcoin network, its value started to rise. In 2010, an early adopter used BTC to buy pizza from a Florida-based pizzeria, marking one of the first real-world transactions using this cryptocurrency. The price of a single BTC remained relatively low until 2013 when it experienced a significant surge, reaching over $1,000 for the first time.

The rise in value attracted investors and media attention, but also sparked concerns about Bitcoin's volatility and security. Regulatory bodies began to take notice, leading to debates about how best to regulate this new financial instrument without stifling innovation.

Despite these challenges, BTC continued to evolve. Improvements in mining hardware, blockchain technology, and user adoption contributed to its growing popularity. In 2017, Bitcoin reached an all-time high of nearly $20,000 per coin before experiencing a dramatic drop in value.

Today, Bitcoin remains one of the most well-known cryptocurrencies globally, with a dedicated following and significant market capitalization. Its journey serves as a testament to the power of innovation and the resilience of digital currencies in an ever-changing financial landscape. As regulations continue to develop and technological advancements push the boundaries of what's possible, Bitcoin's future remains uncertain but promising.

In [22]:
def query_data_mistral(data_json, question, model_name):
    prompt = f"Based on the following relational data, answer the question:\n{data_json}\nQuestion: {question}"
    
    # No Ollama, usamos client.chat()
    chat_response = client.invoke(prompt)
    
    # Retorna a resposta gerada
    return chat_response

# Limitar os dados
limited_data = data.head(500)

# Converter DataFrame para JSON
data_json = limited_data.to_json(orient='records')

# Modelo Mistral no Ollama
model_name = 'mistral'  # ou 'mistral-7b', dependendo do que você baixou com `ollama pull`

# Pergunta de teste
question = "Summarize the text"

# Chamada
resposta = query_data_mistral(data_json, question, model_name)
print(resposta)

 The text provides a list of service requests (solicitations) for various equipment and systems in transportation locations such as bus stops, diesel stations, and television stations. Each solicitation includes information about the affected equipment or system, its location, the reporting center, the sub-location within the center, the time of the issue, the issue description, and the responsible person to fix it. Some common issues include malfunctions with escalators, automated systems, CCTV cameras, and vehicular movement systems. The solicitations have varying levels of priority, from low (Baixa) to medium (Media).

In [24]:
%pip install streamlit Pillow

Collecting streamlit
  Using cached streamlit-1.49.1-py3-none-any.whl.metadata (9.5 kB)
Collecting Pillow
  Downloading pillow-11.3.0-cp311-cp311-win_amd64.whl.metadata (9.2 kB)
Collecting altair!=5.4.0,!=5.4.1,<6,>=4.0 (from streamlit)
  Downloading altair-5.5.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<7,>=4.0 (from streamlit)
  Downloading cachetools-6.2.0-py3-none-any.whl.metadata (5.4 kB)
Collecting click<9,>=7.0 (from streamlit)
  Downloading click-8.2.1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy<3,>=1.23 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from streamlit) (2.3.2)
Requirement already satisfied: packaging<26,>=20 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from streamlit) (2.3.2)
Collecting protobuf<7,>=3.20 (from streamlit)
  Downloading protobuf-6.32.0-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-21.0.0-cp311-cp311-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: requests<3,>=2.27 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from streamlit) (9.1.2)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from streamlit) (4.15.0)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.45-py3-none-any.whl.metadata (13 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from streamlit) (6.5.2)
Collecting jinja2 (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit)
  Downloading jsonschema-4.25.1-py3-none-any.whl.metadata (7.6 kB)
Collecting narwhals>=1.14.2 (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit)
  Downloading narwhals-2.2.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: colorama in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.8.3)
Collecting MarkupSafe>=2.0 (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit)
  Downloading MarkupSafe-3.0.2-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit)
  Downloading attrs-25.3.0-py3-none-any.whl.metadata (10 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit)
  Downloading jsonschema_specifications-2025.4.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit)
  Downloading referencing-0.36.2-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit)
  Downloading rpds_py-0.27.1-cp311-cp311-win_amd64.whl.metadata (4.3 kB)
Requirement already satisfied: six>=1.5 in d:\mestrado\teste\langchain_test\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.49.1-py3-none-any.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------  10.0/10.0 MB 56.4 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 44.7 MB/s  0:00:00
Downloading pillow-11.3.0-cp311-cp311-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ------------------------- -------------- 4.5/7.0 MB 20.7 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 25.4 MB/s  0:00:00
Downloading altair-5.5.0-py3-none-any.whl (731 kB)
   ---------------------------------------- 0.0/731.2 kB ? eta -:--:--
   ---------------------------------------- 731.2/731.2 kB 29.3 MB/s  0:00:00
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-6.2.0-py3-none-any.whl (11 kB)
Downloading click-8.2.1-py3-none-any.whl (102 kB)
Downloading gitpython-3.1.45-py3-none-any.whl (208 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading protobuf-6.32.0-cp310-abi3-win_amd64.whl (435 kB)
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--
   ---------------------------------------- 6.9/6.9 MB 53.1 MB/s  0:00:00
Downloading smmap-5.0.2-py3-none-any.whl (24 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading jsonschema-4.25.1-py3-none-any.whl (90 kB)
Downloading attrs-25.3.0-py3-none-any.whl (63 kB)
Downloading jsonschema_specifications-2025.4.1-py3-none-any.whl (18 kB)
Downloading MarkupSafe-3.0.2-cp311-cp311-win_amd64.whl (15 kB)
Downloading narwhals-2.2.0-py3-none-any.whl (401 kB)
Downloading pyarrow-21.0.0-cp311-cp311-win_amd64.whl (26.2 MB)
   ---------------------------------------- 0.0/26.2 MB ? eta -:--:--
   ---------------------- ----------------- 14.9/26.2 MB 67.3 MB/s eta 0:00:01
   ---------------------------------------  26.2/26.2 MB 72.3 MB/s eta 0:00:01
   ---------------------------------------- 26.2/26.2 MB 55.5 MB/s  0:00:00
Downloading referencing-0.36.2-py3-none-any.whl (26 kB)
Downloading rpds_py-0.27.1-cp311-cp311-win_amd64.whl (228 kB)
Installing collected packages: watchdog, toml, smmap, rpds-py, pyarrow, protobuf, Pillow, narwhals, MarkupSafe, click, cachetools, blinker, attrs, referencing, jinja2, gitdb, pydeck, jsonschema-specifications, gitpython, jsonschema, altair, streamlit

   ----------------------------------------  0/22 [watchdog]
   ----------------------------------------  0/22 [watchdog]
   ----------------------------------------  0/22 [watchdog]
   ----------------------------------------  0/22 [watchdog]
   ----------------------------------------  0/22 [watchdog]
   - --------------------------------------  1/22 [toml]
   --- ------------------------------------  2/22 [smmap]
   --- ------------------------------------  2/22 [smmap]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   ------- --------------------------------  4/22 [pyarrow]
   --------- ------------------------------  5/22 [protobuf]
   --------- ------------------------------  5/22 [protobuf]
   --------- ------------------------------  5/22 [protobuf]
   --------- ------------------------------  5/22 [protobuf]
   --------- ------------------------------  5/22 [protobuf]
   --------- ------------------------------  5/22 [protobuf]
   --------- ------------------------------  5/22 [protobuf]
   --------- ------------------------------  5/22 [protobuf]
   --------- ------------------------------  5/22 [protobuf]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ---------- -----------------------------  6/22 [Pillow]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   ------------ ---------------------------  7/22 [narwhals]
   -------------- -------------------------  8/22 [MarkupSafe]
   ---------------- -----------------------  9/22 [click]
   ---------------- -----------------------  9/22 [click]
   ---------------- -----------------------  9/22 [click]
   ------------------ --------------------- 10/22 [cachetools]
   -------------------- ------------------- 11/22 [blinker]
   --------------------- ------------------ 12/22 [attrs]
   --------------------- ------------------ 12/22 [attrs]
   ----------------------- ---------------- 13/22 [referencing]
   ----------------------- ---------------- 13/22 [referencing]
   ------------------------- -------------- 14/22 [jinja2]
   ------------------------- -------------- 14/22 [jinja2]
   ------------------------- -------------- 14/22 [jinja2]
   ------------------------- -------------- 14/22 [jinja2]
   --------------------------- ------------ 15/22 [gitdb]
   --------------------------- ------------ 15/22 [gitdb]
   --------------------------- ------------ 15/22 [gitdb]
   ----------------------------- ---------- 16/22 [pydeck]
   ----------------------------- ---------- 16/22 [pydeck]
   ----------------------------- ---------- 16/22 [pydeck]
   ----------------------------- ---------- 16/22 [pydeck]
   -------------------------------- ------- 18/22 [gitpython]
   -------------------------------- ------- 18/22 [gitpython]
   -------------------------------- ------- 18/22 [gitpython]
   -------------------------------- ------- 18/22 [gitpython]
   -------------------------------- ------- 18/22 [gitpython]
   ---------------------------------- ----- 19/22 [jsonschema]
   ---------------------------------- ----- 19/22 [jsonschema]
   ---------------------------------- ----- 19/22 [jsonschema]
   ------------------------------------ --- 20/22 [altair]
   ------------------------------------ --- 20/22 [altair]
   ------------------------------------ --- 20/22 [altair]
   ------------------------------------ --- 20/22 [altair]
   ------------------------------------ --- 20/22 [altair]
   ------------------------------------ --- 20/22 [altair]
   ------------------------------------ --- 20/22 [altair]
   ------------------------------------ --- 20/22 [altair]
   ------------------------------------ --- 20/22 [altair]
   ------------------------------------ --- 20/22 [altair]
   ------------------------------------ --- 20/22 [altair]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]
   -------------------------------------- - 21/22 [streamlit]

In [29]:
import streamlit as st
import pandas as pd
import os
from PIL import Image

In [ ]:
import streamlit as st
import pandas as pd
import os
from PIL import Image

# Set Streamlit layout to wide
st.set_page_config(layout="wide")

# Load data from Excel
@st.cache_data
def load_data():
    df = pd.read_excel("D:\\Mestrado\\teste\\langchain_test\\data\\dados.xlsx")

    # Corrigir possíveis espaços/quebras de linha nos nomes das colunas
    df.columns = df.columns.str.strip()
    return df

data = load_data()

# ==============================
# CSS Customizado
# ==============================
st.markdown("""
    <style>
    body {
        background-color: #ffcccb;
    }
    
    .reportview-container .main .block-container {
        background-color: #ffcccb;  /* Light pink background for the main container */
    }

    .sidebar .sidebar-content {
        background-color: #ffcccb;  /* Light pink background for the sidebar */
    }

    .custom-card {
        background-color: white;
        padding: 5px;
        border-radius: 10px;
        border: 2px solid #d3d3d3;
        box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1);
        text-align: center;
        margin-bottom: 10px;
    }

    .custom-card h3 {
        margin-bottom: 2px;
    }

    .custom-card p {
        color: #003366;
        font-size: 20px;
        font-weight: bold;
    }

    .card-container {
        display: flex;
        justify-content: space-between;
        margin-bottom: 10px;
        gap: 10px;
    }

    .centered-title {
        text-align: center;
        font-size: 32px;
        font-weight: bold;
        margin-bottom: 20px;
    }

    .stDataFrame div[data-testid="stHorizontalBlock"] {
        width: auto !important;
        min-width: 150px !important;
    }
    </style>
    """, unsafe_allow_html=True)

# ==============================
# Imagens
# ==============================
image = Image.open('AI Pic3.png')
st.image(image, use_column_width=True, caption="Sales and AI Banner", output_format="PNG")

# Título centralizado
st.markdown('<h1 class="centered-title">FerrovIA Dashboard</h1>', unsafe_allow_html=True)

# Sidebar com imagem
image2 = Image.open('AI Pic1.png')
st.sidebar.image(image2, use_column_width=True)

# ==============================
# Filtros na Sidebar
# ==============================
st.sidebar.header("Filter Options")

hotel_options = data["Bem/Localiz."].dropna().unique() if "Bem/Localiz." in data else []
year_options = data["data_abertura"].dropna().unique() if "data_abertura" in data else []
month_options = data["Hr. Abertura"].dropna().unique() if "Hr. Abertura" in data else []
market_segment_options = data["Prioridade"].dropna().unique() if "Prioridade" in data else []
country_options = data["Reclamante"].dropna().unique() if "Reclamante" in data else []

hotel_filter = st.sidebar.multiselect("Bem/Localiz.", hotel_options, default=list(hotel_options))
year_filter = st.sidebar.multiselect("data_abertura", year_options, default=list(year_options))
month_filter = st.sidebar.multiselect("Hr. Abertura", month_options, default=list(month_options))
market_segment_filter = st.sidebar.multiselect("Prioridade", market_segment_options, default=list(market_segment_options))
country_filter = st.sidebar.selectbox("Reclamante", ["All"] + list(country_options))

# Data Limit filter
data_limit = st.sidebar.slider("Limit Data (Rows)", min_value=10, max_value=120000, value=200)

# ==============================
# Aplicando Filtros
# ==============================
filtered_data = data.copy()

if "Bem/Localiz." in filtered_data:
    filtered_data = filtered_data[filtered_data["Bem/Localiz."].isin(hotel_filter)]

if "data_abertura" in filtered_data:
    filtered_data = filtered_data[filtered_data["data_abertura"].isin(year_filter)]

if "Hr. Abertura" in filtered_data:
    filtered_data = filtered_data[filtered_data["Hr. Abertura"].isin(month_filter)]

if "Prioridade" in filtered_data:
    filtered_data = filtered_data[filtered_data["Prioridade"].isin(market_segment_filter)]

if country_filter != "All" and "Reclamante" in filtered_data:
    filtered_data = filtered_data[filtered_data["Reclamante"] == country_filter]

filtered_data = filtered_data.head(data_limit)

# ==============================
# Métricas
# ==============================
num_rows = len(filtered_data)
num_tokens = num_rows * 21 * 6
num_countries = filtered_data['Reclamante'].nunique() if "Reclamante" in filtered_data else 0
num_cancellations = filtered_data['Contador'].astype(float).sum() if "Contador" in filtered_data else 0

# Cards com métricas
st.markdown('<div class="card-container">', unsafe_allow_html=True)
col1, col2, col3, col4, col5 = st.columns(5)

with col1:
    st.markdown(f'<div class="custom-card"><h3>Number of Rows</h3><p>{num_rows:,}</p></div>', unsafe_allow_html=True)

with col2:
    st.markdown(f'<div class="custom-card"><h3>Est. of Tokens</h3><p>{num_tokens:,}</p></div>', unsafe_allow_html=True)

with col3:
    st.markdown(f'<div class="custom-card"><h3>Number of Countries</h3><p>{num_countries:,}</p></div>', unsafe_allow_html=True)

with col4:
    st.markdown(f'<div class="custom-card"><h3>No. of Cancellations</h3><p>{num_cancellations:,}</p></div>', unsafe_allow_html=True)

st.markdown('</div>', unsafe_allow_html=True)

# ==============================
# Função para consultar modelo
# ==============================
# ATENÇÃO: 'client' e 'model_name' devem estar definidos antes

def query_data(data_json, question):
    prompt = f"Based on the following relational data, answer the question:\n{data_json}\nQuestion: {question}"
    chat_completion = client.invoke(prompt, model=model_name)
    return chat_completion.choices[0].message.content

# ==============================
# Layout com Perguntas e Tabela
# ==============================
col_left, col_right = st.columns(2)

# Perguntas (esquerda)
with col_left:
    st.subheader("Ask a Question About the Data")
    user_question = st.text_input("Enter your question:")

    if st.button("Ask AI"):
        if user_question:
            answer = query_data(filtered_data.to_json(orient="records"), user_question)
            st.subheader("AI Answer")
            st.write(answer)
        else:
            st.warning("Please enter a question.")

# Tabela (direita)
with col_right:
    st.subheader("Filtered Hotel Bookings Data")
    st.dataframe(filtered_data.astype(str))

2025-08-29 22:13:27.135 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.136 No runtime found, using MemoryCacheStorageManager
2025-08-29 22:13:27.354 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.356 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.357 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.358 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.359 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.359 The `use_column_width` parameter has been deprecated and will be removed in a future release. Please utilize the `use_container_width` parameter instead.
2025-08-29 22:13:27.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.428 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.428 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.429 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.430 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.430 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.431 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.434 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:27.434 The `use_column_width` parameter has been deprecated and will be removed in a future release. Please utilize the `use_container_width` parameter instead.
2025-08-29 22:13:27.435 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.006 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.007 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.009 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.010 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.013 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.013 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.014 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.015 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.015 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.016 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.017 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.017 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.019 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.019 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.020 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.022 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.025 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.029 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.030 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.030 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.031 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.033 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.034 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.034 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.036 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.036 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.037 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.037 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.038 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.038 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.092 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.094 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.104 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.107 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.110 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.110 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.111 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.112 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.115 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.117 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.124 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.125 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.126 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.126 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.129 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.129 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.131 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.133 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.134 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.135 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.136 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.137 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.137 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.140 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.141 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.144 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "d:\Mestrado\teste\langchain_test\.venv\Lib\site-packages\streamlit\dataframe_util.py", line 821, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\\table.pxi", line 4795, in pyarrow.lib.Table.from_pandas
  File "d:\Mestrado\teste\langchain_test\.venv\Lib\site-packages\pyarrow\pandas_compat.py", line 637, in dataframe_to_arrays
    arrays = [convert_column(c, f)
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Mestrado\teste\langchain_test\.venv\Lib\site-packages\pyarrow\pandas_compat.py", line 637, in <listcomp>
    arrays = [convert_column(c, f)
              ^^^^^^^^^^^^^^^^^^^^
  File "d:\Mestrado\teste\langchain_test\.venv\Lib\site-packages\pyarrow\pandas_compat.py", line 625, in convert_column
    raise e
  File "d:\Mestrado\teste\langchain_test\.venv\Lib\site-packages\pyarrow\pandas_compat.py", line 619, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\\array.pxi", line 365, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 91, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'datetime.datetime' object", 'Conversion failed for column Unnamed: 7 with type object')
2025-08-29 22:13:28.157 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.158 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-29 22:13:28.158 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.